-- Создание ролей

CREATE ROLE admin WITH LOGIN PASSWORD '*****';
CREATE ROLE customer WITH LOGIN PASSWORD '******';
CREATE ROLE manager WITH LOGIN PASSWORD '*****';

-- Предоставление доступа

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Product TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Category TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Users TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Review TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE OrderDetails TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Orders TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Role TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Cart TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CartDetails TO admin;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Orders TO customer;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE OrderDetails TO customer;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Review TO customer;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Cart TO customer;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CartDetails TO customer;
GRANT SELECT ON TABLE Product TO customer;
GRANT SELECT ON TABLE Category TO customer;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Product TO manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Category TO manager;
GRANT SELECT, UPDATE ON TABLE Orders TO manager;
GRANT SELECT, UPDATE ON TABLE OrderDetails TO manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Review TO manager;
GRANT SELECT ON TABLE Cart TO manager;
GRANT SELECT ON TABLE CartDetails TO manager;

